# Site settings
title: 0x65 Geek Space
email: 0x65@0x65.io
description: "非盈利Geek基地"
baseurl: ""
url: "http://0x65geekspace.github.io"
twitter_username: "0x65"
#github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty